import Head from "next/head";
import { useState } from "react";
import SideNav from "../components/sidenav";
import { work } from "../lib/data.js";
import Link from "next/link";
import Layout from '../components/layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Inez Escandón&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        ></link>
      </Head>
      <Layout
          isWork={false}
          selectedSection={""}
        >
        <section className="p-10 w-full lg:w-9/12 lg:ml-auto">
          <div id="work" className="md:grid md:grid-cols-2">
            <p className="md:col-span-2 mb-5 text-4xl font-semibold">Hola! My name is <span className="text-5xl font-medium font-dawningOfaNewDay">Inez</span>. I'm a Full Stack Web Developer based out of Houston, TX. <img src="/images/texas.png" alt="texas icon" height="30px" width="30px" className="inline pb-1"></img></p>
            <img src="/images/houston.jpg" alt="houston texas city skyline" className="w-full md:col-span-2 mb-10"></img>
            <hr className="my-3 border-coolBlue border-t-2 col-span-2"></hr>
            {work.map((item, i) => (
              <>
              <div className="my-auto md:col-span-1">
                <p className="uppercase pt-3 my-5 md:pt-0 md:mt-0 md:mb-5 text-2xl font-semibold">{item.title}</p>
                <p>{item.description}</p>
              </div>
              <div key={item.slug} className="p-5 my-5 md:col-span-1">
                <div className="container">
                    <img
                      id="project-image"
                      className="rounded-md shadow-lg w-full image"
                      src={item.image.src[0]}
                      alt={item.image.alt}
                      tabIndex={0}
                      onKeyDown={(e)=>{
                      if (e.key === "Enter" || "") {
                      window.location.href = `/work/${item.slug}`;
                    }
                  }}
                    ></img>
                  <Link href={`/work/${item.slug}`}>
                    <div className="overlay rounded-md cursor-pointer">
                        <div className="middle">
                        <div className="text rounded-md transition duration-300 ease-in-out">See More</div>
                    </div>
                    </div>
                  </Link>
                </div>
              </div>
              {i + 1 !== work.length ? <hr className="my-3 text-platinum col-span-2"></hr> : null }
              </>
            ))}
          </div>
        </section>
      </Layout>
    </>
  );
}
