import Head from "next/head";
import { useState } from "react";
import SideNav from "../components/sidenav";
import { work } from "../lib/data.js";
import Link from "next/link";

export default function Home() {
  const [selectedSection, setSelectedSection] = useState("work");

  return (
    <>
      <Head>
        <title>Inez Escandóns Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>

      <main className="relative">
        <SideNav
          selectedSection={selectedSection}
          setSelectedSection={setSelectedSection}
        />
        <section className="p-5 w-full lg:w-9/12 lg:ml-auto">
          <div id="work" className="md:grid md:grid-cols-2">
            {/* <h1 className="mt-3 text-4xl">My Work</h1> */}
            {work.map((item, i) => (
              <>
              <div className="p-5 my-auto md:col-span-1">
                <p className="uppercase mb-5 text-2xl font-semibold">{item.title}</p>
                <p>{item.description}</p>
              </div>
              <div key={item.slug} className="p-5 mb-5 md:my-10 md:col-span-1">
                <div>
                  <Link href={`/work/${item.slug}`}>
                    <img
                      id="project-image"
                      className="cursor-pointer rounded-md shadow-lg w-full"
                      src={item.image.src[0]}
                      alt={item.image.alt}
                    ></img>
                  </Link>
                </div>
                {/* <button className="bg-yellow-300 absolute right-12">See More</button> */}
              </div>
              {i + 1 !== work.length ? <hr className="my-3 text-platinum col-span-2"></hr> : null }
              </>
            ))}
          </div>
        </section>
      </main>
    </>
  );
}
